apiVersion: v1
kind: Secret
metadata:
  name: prometheus-k8s-additional-scrape-config
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |-
    - "job_name": "windows-exporter"
      "relabel_configs":
      - "action": "replace"
        "regex": "(.*)"
        "replacement": "$1"
        "source_labels":
        - "__meta_kubernetes_endpoint_address_target_name"
        "target_label": "instance"
      "static_configs":
      - "targets": []
